package main

// generateQueries returns ≥50 semantic questions about DevOps runbooks.
func generateQueries() []string {
	return []string{
		"How do I fix a pod crash loop in Kubernetes?",
		"What are the steps for an OOMKilled incident?",
		"How to handle a node not ready alert?",
		"What should I do when DNS resolution fails?",
		"How to resolve ImagePullBackOff?",
		"What is the rollback plan for a failed deployment?",
		"How do I drain a node safely?",
		"What to check when etcd is unhealthy?",
		"How to scale a deployment during high traffic?",
		"What are the symptoms of disk pressure?",
		"How do I fix an EC2 instance that is unreachable?",
		"What steps for high CPU utilization on AWS?",
		"How to handle RDS replication lag?",
		"What to do when Lambda throttles?",
		"How to resolve S3 bucket policy errors?",
		"What is the procedure for ElastiCache failover?",
		"How do I fix a CloudFront 5xx error?",
		"What to check when ALB health checks fail?",
		"How to handle SQS message backlog?",
		"What are the steps for an RDS slow query?",
		"How do I fix a Docker container that exits with code 1?",
		"What to do when Docker port conflicts occur?",
		"How to resolve a Docker volume mount error?",
		"What steps for registry authentication failure?",
		"How do I prune Docker volumes safely?",
		"What to check when dockerd is unresponsive?",
		"How to rebuild a corrupted Docker image?",
		"What is the recovery plan for a Docker network bridge failure?",
		"How do I fix containerd socket errors?",
		"What to do when buildkit hangs?",
		"How do I resolve a GitHub Actions build timeout?",
		"What steps for a flaky test in CI?",
		"How to handle artifact upload failure?",
		"What to do when ArgoCD sync fails?",
		"How do I rotate CI secrets?",
		"What to check when a GitLab runner is offline?",
		"How to retry a failed Jenkins job?",
		"What is the rollback procedure for a bad deploy?",
		"How do I approve a deployment gate?",
		"What to do when a merge conflict blocks the pipeline?",
		"How do I silence a Prometheus alert?",
		"What steps for metric cardinality explosion?",
		"How to fix a Grafana dashboard 404?",
		"What to do when PagerDuty fails to notify?",
		"How do I tune trace sampling in Jaeger?",
		"What to check when log ingestion lags?",
		"How to handle high error rate alerts?",
		"What is the procedure for Datadog monitor false positives?",
		"How do I restart the ELK stack?",
		"What to do when PostgreSQL connection pool is exhausted?",
		"How do I fix MySQL replication lag?",
		"What steps for a MongoDB deadlock?",
		"How to handle Redis memory exhaustion?",
		"What to do when Elasticsearch shard allocation fails?",
		"How do I reshard a Cassandra cluster?",
		"What is the procedure for promoting a PostgreSQL standby?",
		"How to kill a long-running database query?",
		"What to check when an index is bloated?",
	}
}
